kind: Service
apiVersion: v1
metadata:
  name: notes-app-service
  namespace: notesapp
spec:
  selector:
    app: notes-app-cont
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP

